platform :ios, ‘8.0’
target ‘Graffiti’  do
pod ‘MBProgressHUD’

# U-Share SDK UI模块（分享面板，建议添加）
pod ‘UMengUShare/UI’
pod ‘Masonry’
# 集成微信(完整版14.4M)
pod ‘UMengUShare/Social/WeChat'
# 集成新浪微博(完整版25.3M)
pod ‘UMengUShare/Social/Sina'

end